apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "storage-demo.fullname" . }}-config
data:
  AZURE_STORAGE_ACCOUNT_NAME: {{ .Values.config.storageAccountName | quote }}
  AZURE_STORAGE_CONTAINER_NAME: {{ .Values.config.storageContainerName | quote }}
  AZURE_STORAGE_BLOB_NAME: {{ .Values.config.storageBlobName | quote }}
  AZURE_AI_ENDPOINT: {{ .Values.config.aiEndpoint | quote }}
  AZURE_AI_DEPLOYMENT: {{ .Values.config.aiDeployment | quote }}
  AZURE_AI_EMBEDDING_DEPLOYMENT: {{ .Values.config.aiEmbeddingDeployment | quote }}
  AZURE_SEARCH_ENDPOINT: {{ .Values.config.searchEndpoint | quote }}
  AZURE_SEARCH_INDEX: {{ .Values.config.searchIndex | quote }}