apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | quote }}
  annotations:
    azure.workload.identity/client-id:
      {{ .Values.serviceAccount.clientId | quote }}
